import type { ComponentType } from "react";
import type { StaticImageData } from "next/image";

import blogWithNoPipelineCover from "./2026/07/blog-with-no-pipeline/cover.png";
import buildAndRunCover from "./2026/07/build-and-run-not-just-ship/cover.png";
import fixedPriceCover from "./2026/07/fixed-price-over-hourly/cover.png";

// Blog post registry. Each entry pairs metadata with a static import of its MDX
// body (compiled to a component by @next/mdx). Kept explicit (no fs globbing) so
// it stays type-safe and works identically in dev, build, and the standalone
// Cloud Run server.
//
// Layout — one folder per post, filed by publication date:
//
//   src/content/blog/<YYYY>/<MM>/<slug>/
//     index.mdx   the post body (pure markdown; no JSX, so it cross-posts as-is)
//     cover.png   1000x420 cover, generated by `pnpm cover` (see scripts/)
//
// Mirrors the vault's 01_Journal/YYYY/MM/ convention, and co-locating the cover
// with its post means the asset can never drift from the article it belongs to.
//
// Adding a post: create the folder + index.mdx, run `pnpm cover`, add one entry
// below. `date` must match the YYYY/MM folders the import path points at.
export type PostMeta = {
  slug: string;
  title: string;
  date: string; // ISO yyyy-mm-dd
  excerpt: string;
  readingTime: string;
};

type PostEntry = {
  meta: PostMeta;
  /**
   * The post's 1000x420 cover, statically imported from its own folder so Next
   * fingerprints and serves it. Used as the per-post OpenGraph/Twitter image —
   * without it every post would share the site-wide OG card and every shared
   * link would look identical.
   */
  cover: StaticImageData;
  load: () => Promise<{ default: ComponentType }>;
};

export const posts: PostEntry[] = [
  {
    meta: {
      slug: "blog-with-no-pipeline",
      title: "I had a blog with no pipeline feeding it",
      date: "2026-07-25",
      excerpt:
        "Building in public is central to how this studio works — and I'd built the publishing surface without anything feeding it. Here's the system that fixed it: capture daily, publish weekly, and make the habit structural instead of willed.",
      readingTime: "5 min read",
    },
    cover: blogWithNoPipelineCover,
    load: () => import("./2026/07/blog-with-no-pipeline/index.mdx"),
  },
  {
    meta: {
      slug: "build-and-run-not-just-ship",
      title: "Shipping is the easy part. Running it is the job.",
      date: "2026-07-09",
      excerpt:
        "Most software relationships end at the handoff. Here’s why BezaCore Labs owns the whole lifecycle — build, deploy, and keep it healthy — instead of handing you a repo and walking away.",
      readingTime: "4 min read",
    },
    cover: buildAndRunCover,
    load: () => import("./2026/07/build-and-run-not-just-ship/index.mdx"),
  },
  {
    meta: {
      slug: "fixed-price-over-hourly",
      title: "Why every engagement is fixed-price",
      date: "2026-07-07",
      excerpt:
        "Hourly billing rewards the slow version of the work and leaves you unable to budget. Here’s how fixed scope keeps both sides honest.",
      readingTime: "3 min read",
    },
    cover: fixedPriceCover,
    load: () => import("./2026/07/fixed-price-over-hourly/index.mdx"),
  },
];

export const sortedPosts = [...posts].sort((a, b) => (a.meta.date < b.meta.date ? 1 : -1));

export const getPost = (slug: string): PostEntry | undefined =>
  posts.find((p) => p.meta.slug === slug);
